# Generated by Django 4.2.7 on 2024-02-01 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sessional_co", "0002_alter_sessionaltable_student_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionaltable",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
