# Generated by Django 4.2.7 on 2024-05-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exit_survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitsurvey',
            name='students',
        ),
    ]
