# Generated by Django 4.2.7 on 2024-05-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_survey', '0002_remove_exitsurvey_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='final_marks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
