# Generated by Django 4.2.7 on 2024-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exit_survey', '0003_studentinfo_final_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstudent',
            name='final_subjects',
            field=models.ManyToManyField(to='core.subject'),
        ),
    ]
