# Generated by Django 4.2.7 on 2024-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_survey', '0004_sessionstudent_final_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='co_response',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='final_marks',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
