# Generated by Django 4.2.7 on 2024-07-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exit_survey', '0007_alter_studentinfo_co_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='co_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='final_marks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
