# Generated by Django 4.2.7 on 2023-11-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(to='core.subject'),
        ),
    ]
