# Generated by Django 4.2.7 on 2023-11-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseoutcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutcome',
            name='program_outcome_priority',
        ),
    ]
