# Generated by Django 4.2.7 on 2023-11-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_courseoutcome_program_outcome_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2)),
                ('message', models.TextField()),
                ('program', models.CharField(max_length=120)),
            ],
        ),
    ]
