# Generated by Django 4.2.7 on 2023-11-08 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_programoutcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcome',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='programoutcome',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
