# Generated by Django 4.2.7 on 2023-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courseoutcome_uuid_programoutcome_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutcome',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='programoutcome',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
