# Generated by Django 4.2.7 on 2023-12-05 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_programoutcome_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramEducationalObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("number", models.IntegerField()),
                ("message", models.TextField()),
                ("program", models.CharField(max_length=120)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("CS", "CS"),
                            ("AI/ML", "AI/ML"),
                            ("IOT", "IOT"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
