# Generated by Django 4.2.7 on 2023-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_programeducationalobjective_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoutcome",
            name="program_educational_objective_priority",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseoutcome",
            name="program_specific_outcome_priority",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
