# Generated by Django 4.2.7 on 2023-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_programspecificoutcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(max_length=120)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("CS", "CS"),
                            ("AI/ML", "AI/ML"),
                            ("IOT", "IOT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("college_id", models.CharField(max_length=20)),
                ("college_email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
            ],
        ),
    ]
