# Generated by Django 4.2.7 on 2023-12-10 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_customuser_faculty_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facultyinfo",
            old_name="college",
            new_name="college_name",
        ),
    ]
