# Generated by Django 4.2.7 on 2023-12-10 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_rename_college_facultyinfo_college_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="faculty_info",
        ),
    ]
