# Generated by Django 4.2.7 on 2023-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_customuser_faculty_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_permitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facultyinfo",
            name="college_name",
            field=models.CharField(
                choices=[("GNIOT", "GNIOT"), ("GIMS", "GIMS")], max_length=120
            ),
        ),
    ]
