# Generated by Django 4.2.7 on 2023-12-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_customuser_is_permitted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="core.subject"),
        ),
    ]
