# Generated by Django 4.2.7 on 2024-01-14 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_customuser_subjects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_permitted",
            new_name="is_login_permitted",
        ),
    ]
