# Generated by Django 4.2.7 on 2024-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_rename_is_permitted_customuser_is_login_permitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_editing_table_permitted",
            field=models.BooleanField(default=False),
        ),
    ]
