# Generated by Django 4.2.7 on 2024-01-14 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_customuser_is_editing_table_permitted"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        choices=[
                            ("TABLE_EDIT_ACCESS", "TABLE_EDIT_ACCESS"),
                            ("USER_LOGIN_ACCESS", "USER_LOGIN_ACCESS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_reviewed", "-date_created"],
            },
        ),
    ]
