# Generated by Django 4.2.7 on 2024-01-14 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_accessrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
